name: Docker - GHCR
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.CR_PAT }}

            - name: Build the image
              run: docker build -t ghcr.io/nikitastetskiy/micro-calendario:latest .

            - name: Run tests
              run: docker run -t -v `pwd`:/test ghcr.io/nikitastetskiy/micro-calendario:latest

            - name: Publish to GitHub Container Registry
              run: docker push ghcr.io/nikitastetskiy/micro-calendario:latest
